---
name: Tuxedo Drivers Milestone Release Checker

on:
  schedule:
    # Runs daily at midnight UTC
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      TUXEDO_DRIVERS_VERSION:
        description: "tuxedo drivers version"
        required: false
      FORCE_REPACKAGE:
        description: "Replace package already exists"
        required: true
        default: false
        type: boolean

permissions:
  contents: write
  pull-requests: write

jobs:
  check-and-release:
    env:
      TUXEDO_DRIVERS_VERSION: ${{ github.event.inputs.TUXEDO_DRIVERS_VERSION }}
      FORCE_REPACKAGE: ${{ github.event.inputs.FORCE_REPACKAGE }}
      GITHUB_TOKEN: ${{ secrets.PMR_TOKEN }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set the latest tuxedo-drivers version
        if: env.TUXEDO_DRIVERS_VERSION == ''
        run: |
          TUXEDO_DRIVERS_VERSION=$(curl -s https://api.github.com/repos/tuxedocomputers/tuxedo-drivers/tags | jq -e '.[0].name')
          echo "TUXEDO_DRIVERS_VERSION=${TUXEDO_DRIVERS_VERSION:2:-1}" >> $GITHUB_ENV

      - name: Check if latest version has been released
        if: env.FORCE_REPACKAGE == 'false' || env.TUXEDO_DRIVERS_VERSION != ''
        run: |
          echo "Fetching current version from spec..."
          releases=$(grep -m1 '^Version:' tuxedo-drivers-kmod.spec | awk '{print $2}')

          if [ "$releases" = "${{ env.TUXEDO_DRIVERS_VERSION}}" ]; then
            echo "RELEASE_EXISTS=true" >> $GITHUB_ENV
          else
            echo "RELEASE_EXISTS=false" >> $GITHUB_ENV
            sed -i "s/^Version:.*/Version:  ${{ env.TUXEDO_DRIVERS_VERSION}}/" tuxedo-drivers-kmod.spec
          fi

      - name: Create PR
        id: cpr
        if: env.RELEASE_EXISTS == 'false' || env.FORCE_REPACKAGE == 'true'
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: update to version ${{env.TUXEDO_DRIVERS_VERSION}}
          title: Update driver version to ${{env.TUXEDO_DRIVERS_VERSION}}
          body: Republish a new Tuxedo drivers version
          branch: update-to-${{env.TUXEDO_DRIVERS_VERSION}}
          token: ${{ secrets.PMR_TOKEN }}
          labels: automerge

      - name: Enable auto-merge for PR
        if: steps.cpr.outputs.pull-request-number != ''
        run: |
          gh pr merge ${{ steps.cpr.outputs.pull-request-number }} --auto --squash
        env:
          GITHUB_TOKEN: ${{ secrets.PMR_TOKEN }}
